### ISSUE TITLE
Generated Mesh has missing face.

### ISSUE THREAD

**Issue by DaegyuMin** [codetiger/Font23D#2]
**Describe the bug**

at 2021-02-06, in master branch

below Font2OBJ.cpp file has a bug that generated mesh has missing face.
------------------------------------------------------------------------------------------
for(size_t p = 0; p < contour->PointCount() - 1; ++p) {
			const double* d1 = contour->GetPoint(p);
			const double* d2 = contour->GetPoint(p + 1);
------------------------------------------------------------------------------------------

this code can be changed to fix bug.
------------------------------------------------------------------------------------------
for(size_t p = 0; p < contour->PointCount(); ++p) {
			const double* d1 = contour->GetPoint(p);
			const double* d2 = contour->GetPoint(
				(p == contour->PointCount() - 1)?(0):(p + 1)
			);
------------------------------------------------------------------------------------------

**Comment by codetiger** [comment]
Hi @DaegyuMin,
Thanks for lot for the feedback. I'll update the repo asap.
