### ISSUE TITLE
Cannot get the code to compile - compiler error on ubuntu gcc

### ISSUE THREAD

**Issue by monsterbrain** [codetiger/Font23D#6]
**Describe the bug**
Cannot compile the code using sh compile.sh

**To Reproduce**
1. I'm using gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)
2. I've installed libfreetype6-dev
2. error showing on compiling - mesh.h: In member function ‘int Mesh::addVertex(Vertex)’:
mesh.h:41:90: error: no matching function for call to ‘find(std::vector<Vertex>::iterator, std::vector<Vertex>::iterator, Vertex&)’
   41 |         std::vector<Vertex>::iterator itr = std::find(vertices.begin(), vertices.end(), v);
      |                                                                                          ^

**Desktop (please complete the following information):**
 - OS: Windows 10 / running ubuntu as WSL

**Comment by codetiger** [comment]
Hi @monsterbrain,
The find function is from standard library vector class. Am not sure why you have issues during compiling.

**Comment by monsterbrain** [comment]
I solved it by adding `#include <algorithm>` and it worked fine. Maybe the standard library wasn't included by default I guess in my configuration.

Thanks for the reply.
